DROP TABLE IF EXISTS MACHINES;

CREATE TABLE MACHINES(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR(255),
    PROGRAM VARCHAR(255),
    RPM INTEGER,
    X INTEGER,
    Y INTEGER,
    Z INTEGER   
);